# Colin Harfst
# cph5wr
# 28 November 2016
# lab section 103

CXX=clang++
CXXFLAGS=-Wall -O2
OFILES=middleearth.o traveling.o

.SUFFIZES: .o .cpp

main: 	$(OFILES)
	$(CXX) $(CXXFLAGS) $(OFILES)
	doxygen
